version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
