name: Pull Request

on:
  pull_request:
    # Only run when a PR is opened or commits are made to it per suggestions
    # here: https://github.com/orgs/community/discussions/25161
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Check if branch is ahead of main
        id: check
        run: |
          git fetch origin main
          behind_count=$(git rev-list --left-right --count HEAD...origin/main | cut -f2)
          if [ $behind_count -eq 0 ]; then
            echo "Branch is only ahead of main"
            exit 0
          else
            echo "Branch behind main"
            exit 1
          fi

  pr-format:
    name: PR title format
    runs-on: ubuntu-latest
    needs: check-up-to-date
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Checkout
        uses: actions/checkout@v3
      - uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '^(feat|fix|chore)\:\s(.*)$'
          allowed_prefixes: 'chore,ci,doc,feat,fix,test'
          prefix_case_sensitive: true
